# Project info
site_name: Arctic Unfrozen
site_url: https://arctic-unfrozen.readthedocs.io/
site_description: MongoDB-backed time-series and dataframe database

# Repository info
repo_name: 't1user/arctic_unfrozen'
repo_url: 'https://github.com/t1user/arctic_unfrozen'
edit_uri: edit/master/docs/

markdown_extensions:
  - admonition

theme:
  name: 'readthedocs'

plugins:
    - search

# Pages
nav:
  - Introduction: 'index.md'
  - Quickstart: 'quickstart.md'
  - Configuration: 'configuration.md'
  - Storage Engines:
    - VersionStore: 'versionstore.md'
    - TickStore: 'tickstore.md'
    - ChunkStore: 'chunkstore.md'
  - ChunkStore API Reference: 'chunkstore_api.md'
  - Contributing to Arctic: 'contributing.md'
  - Releasing: 'releasing.md'
  - Users: 'users.md'
  - FAQ: 'faq.md'
  - Python3 Migration Guide: 'migration_py3.md'
